version: '3.8'
services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    environment:
      - MYSQL_PASS=dvwa
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "8082:3000"
    restart: unless-stopped

# Acesse os alvos em:
# DVWA:        http://localhost:8081
# Juice Shop:  http://localhost:8082

